### ISSUE TITLE
Docs - Github token and gitignore

### ISSUE THREAD

**Issue by ayasyrev** [fastai/fastrelease#42]
I think it should be recommendation to add file token with GitHub token to gitignore.

**Comment by PabloRMira** [comment]
> I think it should be recommendation to add file token with GitHub token to gitignore.

I think this is already in the documentation, see README

![image](https://user-images.githubusercontent.com/36644554/103138401-93b32600-46d2-11eb-9090-120571634a17.png)

**Comment by ayasyrev** [comment]
Sorry, missed it.
Thanks!
