### ISSUE TITLE
enhancement: support repo name != library name

### ISSUE THREAD

**Issue by michaelaye** [fastai/fastrelease#86]
Sometimes I am developing a package under a private repo name that isn't the same as the agreed library name and reserved package name on Pypi.

Currently, the Fastrelease class offers the `repo` keyword at instantiation, but the CLI tool `fastrelease_changelog` doesn't support so that my changes are not being found.

The quick solution that I have implemented ready to PR is to add the `repo` keyword into the CLI for `fastrelease_changelog`. 

However, for convenience, it might be more interesting to either create a new settings keyword to configure that, or to fish it out from the `config["git_url"]` which should point to the repo while the `lib_name` being different? (At least that's how it looks for me.)

Following the philosophy of focusing the PRs, I will offer first the small addition of the CLI keyword addition. 

Let me know your opinions on how to make this situation configurable.

**Comment by tcapelle** [comment]
Same as https://github.com/fastai/fastrelease/issues/74
